Repository TechBastic/roadmaps, pull requests merged in 2023-10, with the labels that each got.

#8 Added full stack resourses
  FullStack-Development/README.md
Labels: good first issue, hacktoberfest-accepted, resource

#16 Update README.md
  FullStack-Development/README.md
Labels: good first issue, hacktoberfest-accepted, resource

#14 DevOps resources
  DevOps/README.md
Labels: good first issue, hacktoberfest-accepted, resource

#21 android development resources has been added
  Android-Development/README.md
Labels: good first issue, hacktoberfest-accepted, resource

#9 Added data science resources
  Data-Science/README.md
  README.md
Labels: good first issue, hacktoberfest-accepted, resource

#23 add dsa resources
  Data-Structures/README.md
Labels: hacktoberfest-accepted, resource

#24 Added introduction to accessibility directly from W3C
  FullStack-Development/README.md
Labels: enhancement, hacktoberfest-accepted, resource

#27 blockchain job portals added
  Blockchain-Development/README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#29 Iamsravya patch 1
  Data-Science/README.md
Labels: good first issue, hacktoberfest-accepted, resource
